# Codemagic CI/CD Configuration File for Unsigned iOS Build (.ipa)
# Documentation: https://docs.codemagic.io/yaml/building/

workflows:
  android-apk:
    name: Mr Pepe - Android APK
    max_build_duration: 60
    instance_type: mac_mini_m1 # También se puede usar mac_mini_m1 o linux
    environment:
      flutter: stable
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - jfcc95012309@gmail.com
        notify:
          success: true
          failure: true

  ios-unsigned:
    name: Mr Pepe - iOS Unsigned IPA
    max_build_duration: 120
    instance_type: mac_mini_m1 # Requerido para construir iOS (.ipa)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set iOS deployment target
        script: |
          # Set deployment target to iOS 16.5 (compatible with iPad)
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 16.5;/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS App (.app) without codesigning
        script: |
          flutter build ios --release --no-codesign
      - name: Package Unsigned IPA
        script: |
          mkdir -p build/ios/ipa
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r ../ipa/MrPepeUnsigned.ipa Payload
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - jfcc95012309@gmail.com # Notificar al correo del administrador
        notify:
          success: true
          failure: true
