# Codemagic CI/CD Configuration File
# Documentation: https://docs.codemagic.io/yaml/building/

workflows:
  ios-release:
    name: Chio's Chicken - iOS Release (.ipa)
    max_build_duration: 120
    instance_type: mac_mini_m1 # Requerido para construir iOS (.ipa)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - apple_credentials # Grupo de variables para App Store Connect y Certificados
      vars:
        APP_STORE_APPLE_ID: 1234567890 # Reemplazar con tu ID de aplicación real
        BUNDLE_ID: "com.polleria.elbrasero.el_brasero"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Set up keychain and code signing
        script: |
          keychain initialize
          # Nota: En la interfaz de Codemagic debes configurar las claves de App Store Connect para que este paso descargue y aplique
          # automáticamente los certificados de producción de Apple Developer y perfiles de aprovisionamiento (Provisioning Profiles).
          #
          # app-store-connect fetch-signing-files "$BUNDLE_ID" --project-id "$APP_STORE_APPLE_ID" --create
          # keychain add-certificates
          # xcode-project use-profiles
      - name: Set iOS deployment target
        script: |
          # Firebase Swift packages require iOS 15.0 minimum
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*/IPHONEOS_DEPLOYMENT_TARGET = 15.0;/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS IPA
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - jfcc95012309@gmail.com # Notificar al correo del administrador
        notify:
          success: true
          failure: true
