// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEV6vwOpGss6Shr6Dx0K_YVsjskvhC3sc',
    appId: '1:151579555777:ios:7e0c532b70b67f3172e140',
    messagingSenderId: '151579555777',
    projectId: 'app-polleria-7e98a',
    storageBucket: 'app-polleria-7e98a.firebasestorage.app',
    iosBundleId: 'com.polleria.elbrasero.elBrasero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA98oApRkBpFLL4guT9q0UJP4sU5M6LdK8',
    appId: '1:151579555777:web:6457af9b5a139c2d72e140',
    messagingSenderId: '151579555777',
    projectId: 'app-polleria-7e98a',
    authDomain: 'app-polleria-7e98a.firebaseapp.com',
    storageBucket: 'app-polleria-7e98a.firebasestorage.app',
    measurementId: 'G-44ZLF9KXKL',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA98oApRkBpFLL4guT9q0UJP4sU5M6LdK8',
    appId: '1:151579555777:web:6457af9b5a139c2d72e140',
    messagingSenderId: '151579555777',
    projectId: 'app-polleria-7e98a',
    authDomain: 'app-polleria-7e98a.firebaseapp.com',
    storageBucket: 'app-polleria-7e98a.firebasestorage.app',
    measurementId: 'G-44ZLF9KXKL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEV6vwOpGss6Shr6Dx0K_YVsjskvhC3sc',
    appId: '1:151579555777:ios:7e0c532b70b67f3172e140',
    messagingSenderId: '151579555777',
    projectId: 'app-polleria-7e98a',
    storageBucket: 'app-polleria-7e98a.firebasestorage.app',
    iosBundleId: 'com.polleria.elbrasero.elBrasero',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm8BK4miU1D2D2eWd-w3tYW0MO6Ri1qYY',
    appId: '1:151579555777:android:eb953a44d50bbf7072e140',
    messagingSenderId: '151579555777',
    projectId: 'app-polleria-7e98a',
    storageBucket: 'app-polleria-7e98a.firebasestorage.app',
  );

}